<?php
// Automatically Generated by hoorayos Installer - Sun, 23 Jul 17 19:45:05 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'chendelin');
define('DB_PASS', 'chendelin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'hoorayos');
define('DB_TABLE_PREFIX', '');
?>
