<?php
// Automatically Generated by hoorayos Installer - Thu, 17 Aug 17 16:47:52 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'chendelin');
define('DB_PASS', 'chendelin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'hoorayos');
define('DB_TABLE_PREFIX', '');
?>
