<?php
// Automatically Generated by hoorayos Installer - Fri, 28 Jul 17 14:02:01 +0800
define('DB_TYPE', 'mysql');
define('DB_USER', 'chendelin');
define('DB_PASS', 'chendelin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'hoorayos');
define('DB_TABLE_PREFIX', '');
?>
